/* Top 100 produtos com maior quantidade em estoque. @EMPRESA parametrizado. */
SELECT FIRST 100
    PB.NOME                            AS "label",
    CAST(PE.ESTOQUE AS NUMERIC(12, 2)) AS "value"
FROM PRODUTO_BASE PB
JOIN PRODUTO P          ON P.CODIGOBASEPRODUTO  = PB.CODIGOBASEPRODUTO
JOIN PRODUTO_ESTOQUE PE ON PE.CODIGOPRODUTO     = P.CODIGOPRODUTO
WHERE PE.CODIGOEMPRESA = @EMPRESA
  AND P.DESATIVADO = 'N'
ORDER BY PE.ESTOQUE DESC
